### ISSUE TITLE
The rightmost player slot cannot be set to a CPU

### ISSUE THREAD

**Issue by pfgithub** [Prazon/SPBF-Issues#10]
The buttons for CPU/Cancel go off the screen on the rightmost player slot, making them unclickable.

Normal player slots:

![a normal player slot](https://i.imgur.com/cb991t9.png)

Rightmost slot:

![the rightmost player slot](https://i.imgur.com/4KnJZJP.png)

Screen resolution: 1920x1080
OS: Arch Linux 4.20.7
CPU: Intel i5-6400 (4) @ 3.300GHz
GPU: NVIDIA GeForce GTX 970

**Comment by Prazon** [comment]
Fixed this by moving the options to the other side of the player profile card
