### ISSUE TITLE
Mouse works but the cursor doesn't move (you see the mouse cursor to select options)

### ISSUE THREAD

**Issue by benbrockn** [Prazon/SPBF-Issues#15]
## System Information
- CPU: Ryzen 2700
- GPU: GTX-1080
   - Driver/LLVM version: Nvidia 410.78
- OS:  Xubuntu 18.04.1 LTS 64-bit

## Symptoms 
Mouse works but the cursor doesn't move (you see the mouse cursor to select options)

## Reproduction 
Start and install the game

**Comment by Prazon** [comment]
Fixed in latest, first pass on merging the gamepad and mouse menu inputs
