### ISSUE TITLE
Yells "SPBF" & "Free for all" at the same time when you exit a local game.

### ISSUE THREAD

**Issue by benbrockn** [Prazon/SPBF-Issues#18]
## System Information
- CPU: Ryzen 2700
- GPU: GTX-1080
   - Driver/LLVM version: Nvidia 410.78
- OS:  Xubuntu 18.04.1 LTS 64-bit

## Symptoms 
Seems to yell the game title after local game exit which overlaps the yell for "free-for-all" when you exit a local game. Not sure if it does this for online mode as I haven't been able to get that working.

**Comment by Prazon** [comment]
Fixed in build Negligent Niece 0.0.7
