### ISSUE TITLE
(Not sure if bug or intentional) Cannot change local game type

### ISSUE THREAD

**Issue by benbrockn** [Prazon/SPBF-Issues#19]
## System Information
- CPU: Ryzen 2700
- GPU: GTX-1080
   - Driver/LLVM version: Nvidia 410.78
- OS:  Xubuntu 18.04.1 LTS 64-bit

## Symptoms 
On online game mode (when you host a game) you have several game types to choose from:
* Free for All
* City Trial
* Capture the Flag
* King of the Hill
* Team battle

For a local game, there's only free for all, I don't see an option to change the game type

**Comment by Prazon** [comment]
Gamemodes are yet to be implemented
