### ISSUE TITLE
[Linux] Game crashes randomly when leaving the lobby or the options menu

### ISSUE THREAD

**Issue by NoXPhasma** [Prazon/SPBF-Issues#2]
Sometimes the game crashes when I exit the options menu or the lobby.

[SPBF.log](https://github.com/Prazon/SPBF-Issues/files/2858139/SPBF.log)

OS:  Linux Mint 19.1 Tessa
CPU: AMD Ryzen 7 1700 @ 3.60 GHz
GPU: GeForce GTX 1080 (415.27)
RAM: 32 GB

**Comment by Prazon** [comment]
I think I fixed it with latest build will need to test!

**Comment by Prazon** [comment]
Fixed crash ayyy
