### ISSUE TITLE
"Hitbox" area of the level select back button is off for online mode (host)

### ISSUE THREAD

**Issue by benbrockn** [Prazon/SPBF-Issues#20]
## System Information
- CPU: Ryzen 2700
- GPU: GTX-1080
   - Driver/LLVM version: Nvidia 410.78
- OS:  Xubuntu 18.04.1 LTS 64-bit

## Symptoms 
When you try to host an online game, the "hitbox" area where you can click the back arrow button for the level select, it's off. There's a deadzone in the center of the button, so it's hard to click.

**EDIT** This is only a mouse issue, not a Xbox controller issue. What appears to be happening is that when you try to click that deadzone with the mouse, it doesn't register the click but resets the mouse to the center of the screen -- very weird. all other buttons work fine.

**Comment by Prazon** [comment]
@benbrockn Does this still happen on latest build?

**Comment by benbrockn** [comment]
> @benbrockn Does this still happen on latest build?

Fixed as of Build: 4541578
