### ISSUE TITLE
Characters may appear behind bushes and trees

### ISSUE THREAD

**Issue by GrumpyBorkie** [Prazon/SPBF-Issues#25]
## System Information
- CPU: Intel® Core™ i5-4210U CPU @ 1.70GHz × 4 
- GPU: GeForce 840M/PCIe/SSE2
   - Driver/LLVM version: nvidia 390
- OS:  Ubuntu 18.04.2 LTS

## Symptoms 
On frost map. Characters may appear behind bushes and trees. But after respawns everything seems to be normal. Also camera ir shakey. Also fixes itself after ultime attacks for some period of time.

## Reproduction 

1. Create Local lobby;
2. Choose players and Frost map;
3. Launch match;
4. Observe.

![20190213233631_1](https://user-images.githubusercontent.com/17853884/52920504-c0979480-3315-11e9-9a19-cf996322dcce.jpg)
![20190213233632_1](https://user-images.githubusercontent.com/17853884/52920505-c1302b00-3315-11e9-9385-2cfa169e90ef.jpg)
![20190213233635_1](https://user-images.githubusercontent.com/17853884/52920506-c1302b00-3315-11e9-98bd-4342ac2a1ffa.jpg)
![20190213233639_1](https://user-images.githubusercontent.com/17853884/52920507-c1302b00-3315-11e9-8f99-4479a21a6a9c.jpg)
![20190218001848_1](https://user-images.githubusercontent.com/17853884/52920508-c1c8c180-3315-11e9-95c1-32bcbc9d482a.jpg)

**Comment by Prazon** [comment]
Let me know if this is fixed in lates @GrumpyBorkie
