### ISSUE TITLE
Game crashes with Vulkan renderer sometimes

### ISSUE THREAD

**Issue by NoXPhasma** [Prazon/SPBF-Issues#26]
## System Information
- CPU:AMD Ryzen 1700
- GPU: GTX 1080
   - Driver/LLVM version: nvidia 415.27
- OS:  Linux Mint 19.1

[crashinfo-SPBF.zip](https://github.com/Prazon/SPBF-Issues/files/2875827/crashinfo-SPBF.zip)

## Symptoms 
Game crashes sometimes when I open or close an online lobby. This seems to only happen when using the Vulkan renderer (now default for Linux), wasn't able to reproduce it with OpenGL (`-opengl4`) renderer yet. 

## Reproduction 

Start the game
open online session
close the online session

**Comment by Prazon** [comment]
hoping this is related to an outdated steamworks SDK will research!

**Comment by Rafagars** [comment]
### **System Information**
* CPU: Intel Core i3 4160
* GPU: GTX 750 TI
    * Drivers: Nvidia drivers 415.27
* OS: Linux Mint 19.1

Same issue

[SPBF-CRC_2.log](https://github.com/Prazon/SPBF-Issues/files/2882371/SPBF-CRC_2.log)

**Comment by NoXPhasma** [comment]
This issue seems to be fixed for me. I wasn't able to reproduce the crash with the latest build.

@Rafagars Can you confirm that, or does it still crash for you?
