### ISSUE TITLE
[Linux] When playing with 2 people on local, player 2 always wins

### ISSUE THREAD

**Issue by benbrockn** [Prazon/SPBF-Issues#29]
## System Information
- CPU: Ryzen 2700
- GPU: GTX-1080
   - Driver/LLVM version: Nvidia 410.78
- OS:  Xubuntu 18.04.1 LTS 64-bit
- BUILDID: 4541578

[SPBF.log](https://github.com/Prazon/SPBF-Issues/files/2895668/SPBF.log)

## Symptoms 
Playing 2 player local game with 2 xbox 360 controllers. No matter the actions of player 1, player 2 is always declared the winner.

Scenarios (5 lives):
(1) Player 1 kills Player 2 5x = Player 2 wins
(2) Player 2 suicides 5x (no hits by Player 1) = Player 2 wins
(3) Player 2 suicides 5x (hit a few times by Player 1) = Player 2 wins
(4) Mix of Player 1 killing Player 2, and Player 2 suicides = Player 2 wins

I do not have any additional xbox controllers to try for 3 or 4 players.

**Comment by Prazon** [comment]
Solved
