### ISSUE TITLE
[Linux] Multiple monitors do not work.

### ISSUE THREAD

**Issue by pfgithub** [Prazon/SPBF-Issues#3]
When running the game, the leftmost monitor is used instead of the default one. If you move the game to another monitor, moving your cursor to the game makes your cursor teleport back to your leftmost monitor.

**Comment by NoXPhasma** [comment]
I can confirm this, it's a bug in the Unreal Engine.

**Comment by Prazon** [comment]
Transitioning to Unreal Engine 4.21 should fix this when the time comes

**Comment by NoXPhasma** [comment]
This has been fixed for me with latest update and the transition to Unreal Engine 4.21. Is it fixed for you as well @pfgithub?

**Comment by Prazon** [comment]
Going to mark closed for now
