### ISSUE TITLE
Slow cursor movement with controller

### ISSUE THREAD

**Issue by NoXPhasma** [Prazon/SPBF-Issues#32]
## System Information
- CPU: AMD Ryzen 1700
- GPU: GTX 970
   - Driver/LLVM version: nvidia 418.43
- OS: Linux Mint 19.1
- BUILDID: Negligent Niece 0.2.1

## Symptoms 
Cursor movement with the controller is way too slow in Options menu and Online lobby. Works fine in main menu and local lobby. Gamepad is XBOX One S.

**Comment by Prazon** [comment]
Fixed slow movement but now cursor disappears when leaving online lobby

**Comment by Prazon** [comment]
Solved
