### ISSUE TITLE
[Linux] Two players are controlled at the same time

### ISSUE THREAD

**Issue by GrumpyBorkie** [Prazon/SPBF-Issues#4]
Two players are controlled at the same time on local game with the same Xbox controller. Player 1 and Player 2 pointers appears after launching local lobby. 

Ubuntu 18.04 LTS

**Comment by NoXPhasma** [comment]
I was able to fix that by removing my gamepad (XBOX One S) from the Steam Controller API.

**Comment by NoXPhasma** [comment]
This has been fixed for me with at least the latest update. Gamepad works as expected even when using Steam Controller API. Can you confirm @GrumpyBorkie?

**Comment by Prazon** [comment]
Marking closed for now

**Comment by GrumpyBorkie** [comment]
Yea, i can confirm its fixed.
