### ISSUE TITLE
[Linux] Game Icon/Picture is not shown in Big Picture mode in Steam. 

### ISSUE THREAD

**Issue by GrumpyBorkie** [Prazon/SPBF-Issues#9]
Game Icon/Picture is not shown in Big Picture mode in Steam. 
It shows only name and default Steam background.

**Comment by Prazon** [comment]
@GrumpyBorkie Let me know if this still happens, I submitted icons for linux but I'm not sure about big picture mode icons

**Comment by GrumpyBorkie** [comment]
In normal Steam window icons are fine, but in Big Picture mode it should be different size. Attaching screenshot.
![screenshot from 2019-02-22 01-26-55](https://user-images.githubusercontent.com/17853884/53209213-7c243580-3642-11e9-85a4-cd9cbbc204d3.png)

**Comment by Prazon** [comment]
Solved
